Add divise
Grandi0z/blog_rails pull request #9
Opened 2023-10-23 21:23 UTC by Grandi0z

### This pull request adds features related to authentication.
#### Changes made :
- Add gem Divise
- Add a register page for new users.
- Added login page 

####Note:
![andrea](https://github.com/Grandi0z/blog_rails/assets/114248080/efcfd1c5-35ba-462a-b85f-9fbf6e12bf94)
 Why I'm working alone :

2023-10-23 22:18 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi @Grandi0z , 
![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow is correctly. ✔
- `Devise` has successfully been set up. ✔


## Required Changes ♻️

- [ ] Please, I strongly advise you to remove the commented code in your navbar partial because leaving commented code in your code base is not a good practice and makes your code look cluttered.👌😊

### Nav bar partial :point_down: 

![Screenshot from 2023-10-23 22-29-32](https://github.com/Grandi0z/blog_rails/assets/89228743/65c9ae30-d0a1-4f18-97fe-6c74ee6720aa)




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-23 22:18 UTC, ridwanediallo commented on app/views/devise/sessions/new.html.erb
> +    <%= f.email_field :name, autofocus: true, autocomplete: "email" %>
- [ ] Great job adding `devise` to your project 👏. However, after signing up, I am not able to log in. I'm getting an error: `Unpermitted parameter: :name.` . The issue is in the login form in the `email` input field, you are setting the attribute to `:name` however, `devise` expects it to be `:email` attribute. Please ensure to fix it so we can successfully sign in after signing up. :ok_hand:  😊

```suggestion
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
```

2023-10-23 22:18 UTC, ridwanediallo commented on app/views/devise/sessions/new.html.erb
> +    <%= f.email_field :name, autofocus: true, autocomplete: "email" %>
- [ ] As stated in the requirement, I would kindly suggest that you ensure that the `UI design` of your `login` page looks similar to the provided [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_login.png). :ok_hand: 

### Requirement :point_down: 
![Screenshot from 2023-10-23 22-00-44](https://github.com/Grandi0z/blog_rails/assets/89228743/084e2629-5369-495e-8fea-94523758bc41)

### your login form :point_down: 
![Screenshot from 2023-10-23 22-04-34](https://github.com/Grandi0z/blog_rails/assets/89228743/3ddd3c5c-b350-49e6-ac8a-2c8571cb3cd4)

### the wireframe :point_down: 
![Screenshot from 2023-10-23 22-05-58](https://github.com/Grandi0z/blog_rails/assets/89228743/e65070ad-68e6-4ea9-ad59-50db497ad155)

2023-10-23 22:18 UTC, ridwanediallo commented on app/views/devise/registrations/new.html.erb
> +<% end %>
- [ ] Last, by not least, I would kindly suggest you ensure that the `UI design` of your `sign up` page looks similar to the provided [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_login.png) as well.  👍️

### Requirement :point_down: 
![Screenshot from 2023-10-23 22-00-44](https://github.com/Grandi0z/blog_rails/assets/89228743/084e2629-5369-495e-8fea-94523758bc41)

### Your sign-up form :point_down: 
![Screenshot from 2023-10-23 22-04-29](https://github.com/Grandi0z/blog_rails/assets/89228743/89df6527-b53c-4563-894a-a45924446bb9)


### the wireframe :point_down: 
![Screenshot from 2023-10-23 22-05-58](https://github.com/Grandi0z/blog_rails/assets/89228743/e65070ad-68e6-4ea9-ad59-50db497ad155)

2023-10-24 13:13 UTC, Reem-lab requested changes
# Hi @Grandi0z, 👋🏻👋🏻 

Great work on making the changes requested by a previous reviewer 👏🔥✨💯🎉 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- [ ]  Followed Gitflow 💯
- [ ]  Descriptive PR⭐
- [ ]  Kudos for working on the set up the devise🤩
- [ ]  No Linters error ✅
- [ ]  Good job working on the requested changes ✨

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-24 13:13 UTC, Reem-lab commented on app/views/partials/_navbar.html.erb
> +#   <%# end %>
- [ ]  Please, I strongly advise you to remove the commented code in your navbar partial because leaving commented code in your code base is not a good practice and makes your code look cluttered.👌😊 as requested by the previous reviewer 💯✨

2023-10-24 13:48 UTC, danmainah approved these changes
Hi @Grandi0z , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️  Implemented the change requested to ensure the codebase doesn't have commented code.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-24 17:10 UTC, merged